{{- if .Values.networkpolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "host" . | quote }}
spec:
  policyTypes:
  - Ingress
  ingress:
  {{- if .Values.networkpolicy.from }}
  - from: {{ toYaml .Values.networkpolicy.from | nindent 4 }}
    ports:
    - port: 5432
      protocol: TCP
  {{- end }}
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.cnpg.namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.cnpg.name }}
          {{- if default .Values.cnpg.instance false }}
          app.kubernetes.io/instance: {{ .Values.cnpg.instance }}
          {{- end }}
    ports:
    - protocol: TCP
      port: 8000
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ include "host" . | quote }}
      cnpg.io/podRole: instance
{{- end }}