{{- $size := .Values.size  -}}
{{- $walSize := .Values.walsize | default $size -}}
{{- $globalPg := dig "global" "postgresql" (dict) ( .Values | toJson | fromJson) -}}
---
# https://cloudnative-pg.io/documentation/1.19/api_reference/#Cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $globalPg.host | default .Values.host | quote  }}
spec:
  instances: {{ .Values.instances }}

  managed:
    services:
      additional:
      - selectorType: rw
        serviceTemplate:
          metadata:
            name: {{ $globalPg.host | default .Values.host | quote  }}
          spec:
            type: LoadBalancer
        updateStrategy: patch

  nodeMaintenanceWindow: # Allow a node maintenace with database interruption
    inProgress: true
    reusePVC: true

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/storage
            operator: In
            values:
            - "true"
    
  storage:
    size: {{ $size | quote  }}
    resizeInUseVolumes: true
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ $size | quote  }}
      volumeMode: Filesystem
  walStorage:
    size: {{ $walSize | quote  }}
    resizeInUseVolumes: true
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ $walSize | quote  }}
      volumeMode: Filesystem

  bootstrap:
    initdb:
      database: {{ $globalPg.database | default .Values.database | quote  }}
      owner: {{ $globalPg.username | default .Values.username | quote  }}
