---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name" . | quote  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "name" . | quote  }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . | quote  }}
  namespace: {{ .Release.Namespace }}
