---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "name" . | quote  }}
spec:
  provider:
    kubernetes: 
      remoteNamespace: {{ .Release.Namespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "name" . | quote  }}
