---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: {{ include "namespace" . | quote  }}
  name: {{ include "name" . | quote  }}
spec:
  provider:
    kubernetes: 
      remoteNamespace: {{ include "namespace" . | quote  }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: {{ include "name" . | quote  }}
