{{- if eq .Values.app.secret.type "sealedSecret" -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  encryptedData:
    APP_SECRET: {{ .Values.app.secret.app }}
    {{- with .Values.app.secret.extraValues }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
{{- end -}}
