{{- if not (eq .Values.app.secret.type "sealedSecret") -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  APP_SECRET: {{ .Values.app.secret.app | b64enc }}
  {{- with .Values.app.secret.extraValues }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}