# Chart.yaml
apiVersion: v2
name: k8s-store
description: k8s-store Helm Chart that creates a SecretStore for local namespace in local kubernetes cluster
type: application
version: 1.0.4
appVersion: 1.0.0

annotations:
  artifacthub.io/changes: |
    - description: SecrteStore version
      kind: fixed

